  File "C:\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Win\work_practice\work-env\lib\site-packages\django\utils\autoreload.py", line 54
, in wrapper
    fn(*args, **kwargs)
  File "C:\Win\work_practice\work-env\lib\site-packages\django\core\management\commands\runs
erver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "C:\Win\work_practice\work-env\lib\site-packages\django\core\management\base.py", lin
e 390, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Win\work_practice\work-env\lib\site-packages\django\core\management\base.py", lin
e 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Win\work_practice\work-env\lib\site-packages\django\core\checks\registry.py", lin
e 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Win\work_practice\work-env\lib\site-packages\django\core\checks\urls.py", line 40
, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "C:\Win\work_practice\work-env\lib\site-packages\django\core\checks\urls.py", line 57
, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "C:\Win\work_practice\work-env\lib\site-packages\django\utils\functional.py", line 80
, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Win\work_practice\work-env\lib\site-packages\django\urls\resolvers.py", line 584,
 in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Win\work_practice\work-env\lib\site-packages\django\utils\functional.py", line 80
, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Win\work_practice\work-env\lib\site-packages\django\urls\resolvers.py", line 577,
 in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Win\work_practice\__Django\try_django_project\try_django_project\urls.py", line 1
9, in <module>
    from .views import (home_page,
  File "C:\Win\work_practice\__Django\try_django_project\try_django_project\views.py", line
10
    if request.user
                  ^
SyntaxError: invalid syntax

C:\Win\work_practice\__Django\try_django_project\try_django_project\views.py changed, reload
ing.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
October 09, 2019 - 16:52:01
Django version 2.2.6, using settings 'try_django_project.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
C:\Win\work_practice\__Django\try_django_project\try_django_project\views.py changed, reload
ing.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
October 09, 2019 - 16:53:03
Django version 2.2.6, using settings 'try_django_project.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[09/Oct/2019 16:53:07] "GET /home HTTP/1.1" 301 0
[09/Oct/2019 16:53:07] "GET /home/ HTTP/1.1" 200 1437
Not Found: /home1/
[09/Oct/2019 16:53:11] "GET /home1/ HTTP/1.1" 404 2710
C:\Win\work_practice\__Django\try_django_project\try_django_project\urls.py changed, reloadi
ng.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
October 09, 2019 - 16:53:25
Django version 2.2.6, using settings 'try_django_project.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Not Found: /homee/
[09/Oct/2019 16:53:28] "GET /homee/ HTTP/1.1" 404 2710
[09/Oct/2019 16:53:31] "GET /homee HTTP/1.1" 200 1773
[09/Oct/2019 16:53:59] "GET /homee HTTP/1.1" 200 1526
C:\Win\work_practice\__Django\try_django_project\try_django_project\views.py changed, reload
ing.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
October 09, 2019 - 16:56:50
Django version 2.2.6, using settings 'try_django_project.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

(work-env) C:\Win\work_practice\__Django\try_django_project>python manage.py

Type 'manage.py help <subcommand>' for help on a specific subcommand.

Available subcommands:

[auth]
    changepassword
    createsuperuser

[contenttypes]
    remove_stale_contenttypes

[django]
    check
    compilemessages
    createcachetable
    dbshell
    diffsettings
    dumpdata
    flush
    inspectdb
    loaddata
    makemessages
    makemigrations
    migrate
    sendtestemail
    shell
    showmigrations
    sqlflush
    sqlmigrate
    sqlsequencereset
    squashmigrations
    startapp
    startproject
    test
    testserver

[sessions]
    clearsessions

[staticfiles]
    collectstatic
    findstatic
    runserver

(work-env) C:\Win\work_practice\__Django\try_django_project>ls
'ls' is not recognized as an internal or external command,
operable program or batch file.

(work-env) C:\Win\work_practice\__Django\try_django_project>ls
'ls' is not recognized as an internal or external command,
operable program or batch file.

(work-env) C:\Win\work_practice\__Django\try_django_project>python manage.py

Type 'manage.py help <subcommand>' for help on a specific subcommand.

Available subcommands:

[auth]
    changepassword
    createsuperuser

[contenttypes]
    remove_stale_contenttypes

[django]
    check
    compilemessages
    createcachetable
    dbshell
    diffsettings
    dumpdata
    flush
    inspectdb
    loaddata
    makemessages
    makemigrations
    migrate
    sendtestemail
    shell
    showmigrations
    sqlflush
    sqlmigrate
    sqlsequencereset
    squashmigrations
    startapp
    startproject
    test
    testserver

[sessions]
    clearsessions

[staticfiles]
    collectstatic
    findstatic
    runserver

(work-env) C:\Win\work_practice\__Django\try_django_project>python manage.py startapp blog

(work-env) C:\Win\work_practice\__Django\try_django_project>python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  No migrations to apply.

(work-env) C:\Win\work_practice\__Django\try_django_project>python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applie
d.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate'
 to apply them.

(work-env) C:\Win\work_practice\__Django\try_django_project>python manage.py makemigration
Unknown command: 'makemigration'. Did you mean makemigrations?
Type 'manage.py help' for usage.

(work-env) C:\Win\work_practice\__Django\try_django_project>python manage.py makemigrations
Migrations for 'blog':
  blog\migrations\0001_initial.py
    - Create model BlogPost

(work-env) C:\Win\work_practice\__Django\try_django_project>python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, blog, contenttypes, sessions
Running migrations:
  Applying blog.0001_initial... OK

(work-env) C:\Win\work_practice\__Django\try_django_project>python manage.py shell
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:05:16) [MSC v.1915 32 bit (Intel)] on win32

Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from blog.models import BlogPost
>>> obj1 = BlogPost()
>>> obj2 = BlogPost()
>>> obj1.title = "This is my first title"
>>> obj1.content = "This is my first content"
>>> exit
Use exit() or Ctrl-Z plus Return to exit
>>> exit()

(work-env) C:\Win\work_practice\__Django\try_django_project>python manage.py shell
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:05:16) [MSC v.1915 32 bit (Intel)] on win32

Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> obj.title
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'obj' is not defined
>>> obj1.title
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'obj1' is not defined
>>> from blog.models import BlogPOst
Traceback (most recent call last):
  File "<console>", line 1, in <module>
ImportError: cannot import name 'BlogPOst' from 'blog.models' (C:\Win\work_practice\__Django
\try_django_project\blog\models.py)
>>> from blog.models import BlogPost
>>> obj1.title
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'obj1' is not defined
>>> from blog.models import BlogPost
>>> obj1 = BlogPost()
>>> obj1.title = "This is my first title of obj1"
>>> obj1.content = "This is my first content of obj1"
>>> obj1.save()
>>> exit()

(work-env) C:\Win\work_practice\__Django\try_django_project>python manage.py shell
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:05:16) [MSC v.1915 32 bit (Intel)] on win32

Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> obj1.title
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'obj1' is not defined
>>> from blog.models import BlogPost
>>> obj1.title
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'obj1' is not defined
>>> obj1 = BlogPost.objects.get(title='This is my first title of obj1')
>>> obj1.title
'This is my first title of obj1'
>>> obj1.content
'This is my first content of obj1'
>>>